taxi_rides_ny:
  outputs:
    dev:
      type: duckdb
      path: ../data/taxi_rides_ny.duckdb
      schema: dev
      threads: 1
      extensions:
        - parquet
      settings:
        memory_limit: "32GB"
        # Faster insertion if the external query doesn't contain ORDER BY
        preserve_insertion_order: false

    prod:
      type: duckdb
      path: ../data/taxi_rides_ny.duckdb
      schema: prod
      threads: 1
      extensions:
        - parquet
      settings:
        memory_limit: "32GB"
        # Faster insertion if the external query doesn't contain ORDER BY
        preserve_insertion_order: false

  target: dev
